### PR TITLE
feat: add the ability to create transient search buffers

### PR DESCRIPTION
**Pull request by mehalter**
When opening grug, it essentially creates a "temporary window" which I don't want to show up in my tabline/bufferline plugins. This makes it so that the buffer is unlisted similar to other similar plugins such as `nvim-spectre`.

Thanks so much for an awesome plugin!

### CODE REVIEW

**Comment by mehalter** [comment]
It looks like this has made the tests fail. Honestly looking at the code it looks like this is exposing a different bug in the code. If you run `Make launch-test-instance` and start searching. Every time you go from having nothing in the search to having something in the search the title increments. It looks like the code for updating the buffer title is incorrect. I'm not sure why it's working without this change honestly. Once the title of the buffer changes to be suffixed with `: <search_tem>` it shouldn't work fetching a buffer number when looking up if a buffer exists. This might be something that needs to be looked into. I tried and I can't figure out how the logic is supposed to be working here. Sorry! Let me know if I can help in any way!

**Comment by mehalter** [comment]
Ok, I spent a while trying to figure this out. For some reason when the buffer is unlisted it continously makes more buffers 🤔 So when it's trying to see if a buffer exists with a given number it gets the last buffer number rather than the current one. I honestly cant figure out what is causing it to make so many unlisted, hidden buffers 🤔

**Comment by folke** [comment]
I did add the creation of a scratch buffer for file type detection in utils. Is that what's causing the issue?
Not home right now, so can't check

**Comment by mehalter** [comment]
Nope! Even if I revert back to before all of those commits it still occurs. It actually seems to be some sort of default vim/neovim behavior of `vim.api.nvim_buf_set_name`. I am still looking to see if this is intended behavior or if it's a bug upstream in core neovim. Here are steps:

1. `nvim --clean`, start a completely stock neovim session
2. `:lua =vim.api.nvim_create_buf(false, true)`, create an unlisted/scratch buffer (make note of returned bufnr, assuming here 2)
3. `:lua vim.api.nvim_buf_set_name(2, "hello")`, set the buffer name to "hello"
4. `:ls!`, see that the buffer is named "hello"
5. `:lua vim.api.nvim_buf_set_name(2, "test")`, set the buffer name to "test"
6. `:ls!`, see that the buffer is named "test" but there is now a new buffer with the old name of "hello"
7. `:lua vim.api.nvim_buf_set_name(2, "welp")`, set the buffer name to "welp"
8. `:ls!`, see that the buffer is named "welp" but there is now a new buffer with the old name of "test" alongside our other buffer named "hello"

**Comment by mehalter** [comment]
https://github.com/neovim/neovim/issues/20349

Hm. It seems like there is not built in method to rename a buffer without creating duplicates that hold the old buffer name

**Comment by mehalter** [comment]
Ok as was described in the issue linked above, this can be avoided in a performant manner using ffi. I added a new utility that renames a buffer without creating these placeholder, empty buffers

**Comment by MagicDuck** [comment]
@mehalter my mind is literally blown away by the depth of this investigation and the solution! 🤯 

Regarding having the buffer unlisted though, the way it's designed atm, especially with the name updates, it's actually a valid workflow to have it listed. The reasoning behind this is that sometimes it's useful to have multiple "saved searches" laying around that you can refer back to when you need them. I think this probably stems from a difference in implementation of search and replace in VSCode vs Intellij Idea (or similar editors). The first implements it as a throw away temporary thing while the latter gives you the option to save the search results. Depending on what you have in your history of usage you tend to think one way or the other, but I think both approaches can be useful.

As such, I think what we should add on top of what you already have in this PR is:
1. add an `unlisted` (boolean) option (of some other name if we can think of a better one). Default it to `false` to keep behaviour consistent with what we've had so far.
2. use that when creating the far buffer: `local buf = vim.api.nvim_create_buf(context.options.unlisted, true)`
3. if `options.unlisted` is `true`, add an autocommand to delete the buffer when the window is deleted, since it makes no sense to keep it around as you can't reach it. (suggested location to to this is in `setupCleanup()` in `grug-far.lua`)

**Review by MagicDuck — CHANGES_REQUESTED** [review]
needs slight changes as per previous comment

**Comment by mehalter** [comment]
Thanks for the feedback @MagicDuck ! I just added a `transient` option which controls if the buffer should be unlisted and wipe on hidden. Let me know what you think!

Also when adding the docstring I believe I noticed an incorrect docstring for `wrap`. Let me know if this is incorrect and I should revert that change.

**Comment by folke** [comment]
Instead of using ffi, wouldn't it be better to delete the other buffer?

**Review by MagicDuck — APPROVED** [review]
I like it! Approved! Thanks for also fixing the wrap thingy 🎈

**Comment by folke** [comment]
Great. Updated LazyVim to use the new option. ty!

**Comment by MagicDuck** [comment]
I am guessing ffi is more efficient, no? But at a somewhat higher risk of breaking since not officially publicly exposed. I would think that api would change very rarely if at all though.

**Comment by mehalter** [comment]
oh my goodness. I'm so sorry, I got the polarity wrong on my listing 🤦🏼 Opening a followup PR now....

**Comment by MagicDuck** [comment]
No worries 😄

**Comment by mehalter** [comment]
> Instead of using ffi, wouldn't it be better to delete the other buffer?

I was thinking about this as well. There isn't a very performant way of finding this out from what I was looking at. The function doesn't directly return the buffer number of what it creates. So you have to do a search based on the old name. If there is another buffer that happens to have that name then you will discover it. Do you have any way to figure this out in a way that guarantees correctness? In an ideal world it would be nice to not rely on ffi

**Comment by folke** [comment]
buffer names are unique in Neovim, so should be pretty straightforward no?

**Comment by folke** [comment]
```lua
local function rename(buf, name)
  local old = vim.api.nvim_buf_get_name(buf)
  vim.api.nvim_buf_set_name(buf, name)
  for _, b in ipairs(vim.api.nvim_list_bufs()) do
    if vim.api.nvim_buf_get_name(b) == old then
      vim.api.nvim_buf_delete(b, { force = true })
      break
    end
  end
end

local buf = vim.api.nvim_create_buf(false, true)
rename(buf, "foo1")
rename(buf, "foo2")
rename(buf, "foo3")
```

**Comment by mehalter** [comment]
I thought that buffer names are not necessarily unique, they are just typically unique. When I get back to my computer tomorrow I can double check this

**Comment by folke** [comment]
They are unique. Just try setting the name to an existing name.
Buffer names in Neovim are actually ids. Typically the filename.

**Comment by folke** [comment]
```
:f[ile][!] {name}	Sets the current file name to {name}.  The optional !
			avoids truncating the message, as with |:file|.
			If the buffer did have a name, that name becomes the
			|alternate-file| name.  An unlisted buffer is created
			to hold the old name.
```

So basically deleting the alternate buffer also should do the trick.

See also https://github.com/lewis6991/brodir.nvim/blob/f4bac3196483d320ca06232df0cb2c1b0d09439c/lua/brodir.lua#L135

**Comment by mehalter** [comment]
> ```
> :f[ile][!] {name}	Sets the current file name to {name}.  The optional !
> 			avoids truncating the message, as with |:file|.
> 			If the buffer did have a name, that name becomes the
> 			|alternate-file| name.  An unlisted buffer is created
> 			to hold the old name.
> ```
> 
> So basically deleting the alternate buffer also should do the trick.
> 
> See also https://github.com/lewis6991/brodir.nvim/blob/f4bac3196483d320ca06232df0cb2c1b0d09439c/lua/brodir.lua#L135

I actually tried that exact code and it doesn't work. On startup of the test environment it incorrectly identifies the empty buffer on startup as the alternative buffer.

**Comment by mehalter** [comment]
@folke I have investigated this a bit more. Using the following script saved as `test.lua`:

```lua
local test_buf = vim.api.nvim_create_buf(false, true)
local i = 1
local start = os.clock()
while true do
  if i > 100000 then
    print(('100,000 renames took: %s seconds'):format(os.clock() - start))
    return
  end
  require('grug-far.utils').buf_set_name(test_buf, ('new name %s'):format(i))
  i = i + 1
end
```

ran from the root of this repo cloned with `nvim -u scripts/minimal_init.lua -l test.lua`

Here are the results:

| Method | Execution Time (s) |
|---|---|
| FFI | 1.520053 |
| `#` to directly get alternative buffer | 8.016086 |
| looping to get buffer with old name | 7.575559 |

> [!NOTE]
> The method for looping in this case was tested in an environment with the _minimal_ number of buffers. The execution time would increase as the user has more buffers

So it seems like the FFI method does have speedup of nearly 5x over the next fastest method. It might be a good idea to stick with it honestly.


<details>
<summary>Here is the code I was using for the utility functions in the tests (ffi was tested with the current code on the main branch)</summary>

Use `#` to get the buffer directly:

```lua
function M.buf_set_name(bufnr, name)
  local old_name = vim.api.nvim_buf_get_name(bufnr)
  vim.api.nvim_buf_set_name(bufnr, name)
  if old_name == '' then
    return
  end
  local new_buf = vim.api.nvim_buf_call(bufnr, function()
    return vim.fn.bufnr('#')
  end)
  if new_buf ~= bufnr and new_buf ~= -1 and vim.api.nvim_buf_get_name(new_buf) == old_name then
    pcall(vim.api.nvim_buf_delete, new_buf, { force = true })
  end
end
```

Loop over all buffers:

```lua
function M.buf_set_name(bufnr, name)
  local old_name = vim.api.nvim_buf_get_name(bufnr)
  vim.api.nvim_buf_set_name(bufnr, name)
  if old_name == '' then
    return
  end
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if buf ~= bufnr and vim.api.nvim_buf_get_name(buf) == old_name then
      vim.api.nvim_buf_delete(buf, { force = true })
      break
    end
  end
end
```
</details>

**Comment by folke** [comment]
Sure, but speed doesn't really matter in this case? It's not renaming it 1000 of times. the performance of just one rename is next to nothing

**Comment by mehalter** [comment]
This is true as well. I can make a follow up PR to remove reliance on the internal stuff for sure

**Comment by mehalter** [comment]
It is interesting that buffer names have to be unique unless they are empty. I added in an extra check just to skip the deletion in the case where the original buffer name was just empty since that can lead to conflicting names. Hopefully that's the only edge case

**Comment by folke** [comment]
Everything related to buffer names seems a bit odd in Neovim tbh. I really didn't know about that rename issue that keeps old buffers around. Super weird.

**Pull request merged**
